import type { AppData, Content, Idea, Script, Sponsor, Channel, CalendarEvent, LibraryItem } from './types'

function uid() {
  return Math.random().toString(36).slice(2, 10)
}

function daysAgo(n: number) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

function daysFromNow(n: number) {
  const d = new Date()
  d.setDate(d.getDate() + n)
  return d.toISOString().split('T')[0]
}

export const seedData: AppData = {
  channels: [
    {
      id: 'ch-1',
      name: 'Tech Talk with Mo',
      platform: 'youtube',
      username: '@techtalkwithmo',
      followers: 12400,
    },
    {
      id: 'ch-2',
      name: 'muad.sehli',
      platform: 'tiktok',
      username: '@muad.sehli',
      followers: 8200,
    },
    {
      id: 'ch-3',
      name: 'muad.sehli',
      platform: 'instagram',
      username: '@muad.sehli',
      followers: 3100,
    },
  ],

  content: [
    {
      id: 'c-1',
      title: 'I Tried AI Tools for 30 Days — Here\'s What Actually Works',
      description: 'A deep dive into the AI tools I used for a month and which ones actually saved me time and money.',
      platform: 'youtube',
      status: 'published',
      thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80',
      publishedAt: daysAgo(3),
      views: 48200,
      likes: 3840,
      comments: 312,
      shares: 890,
      engagementRate: 10.2,
      revenue: 340,
      tags: ['AI', 'Productivity', 'Tech'],
      createdAt: daysAgo(14),
      updatedAt: daysAgo(3),
    },
    {
      id: 'c-2',
      title: 'Build This SaaS in 48 Hours — Full Tutorial',
      description: 'Complete walkthrough building a SaaS from scratch using Next.js, Tailwind, and Stripe.',
      platform: 'youtube',
      status: 'published',
      thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
      publishedAt: daysAgo(10),
      views: 32100,
      likes: 2650,
      comments: 198,
      shares: 540,
      engagementRate: 8.4,
      revenue: 580,
      tags: ['Tutorial', 'SaaS', 'Next.js'],
      createdAt: daysAgo(21),
      updatedAt: daysAgo(10),
    },
    {
      id: 'c-3',
      title: 'This Workflow Changed How I Create Content',
      description: 'My exact content creation workflow that 10x\'d my output without burning out.',
      platform: 'tiktok',
      status: 'scheduled',
      thumbnail: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80',
      scheduledAt: daysFromNow(2),
      views: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      engagementRate: 0,
      revenue: 0,
      tags: ['Workflow', 'Content', 'Productivity'],
      createdAt: daysAgo(5),
      updatedAt: daysAgo(1),
    },
    {
      id: 'c-4',
      title: '5 AI Tools Every Developer Should Use in 2025',
      description: 'Quickfire list of the best AI tools transforming how developers work.',
      platform: 'tiktok',
      status: 'editing',
      views: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      engagementRate: 0,
      revenue: 0,
      tags: ['AI', 'Developer', 'Tools'],
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
    },
    {
      id: 'c-5',
      title: 'Behind the Scenes: My Full Editing Process',
      description: 'Giving viewers a look at how I edit my videos from raw footage to final export.',
      platform: 'instagram',
      status: 'recording',
      views: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      engagementRate: 0,
      revenue: 0,
      tags: ['Behind the Scenes', 'Editing', 'YouTube'],
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
    {
      id: 'c-6',
      title: 'I Built a $3K MRR SaaS in 30 Days — Full Breakdown',
      description: 'Detailed breakdown of how I researched, built, and launched a profitable SaaS in one month.',
      platform: 'youtube',
      status: 'ready_to_script',
      views: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      engagementRate: 0,
      revenue: 0,
      tags: ['SaaS', 'Business', 'Build in Public'],
      createdAt: daysAgo(7),
      updatedAt: daysAgo(7),
    },
    {
      id: 'c-7',
      title: 'Stop Using Notion for Everything',
      description: 'Why I moved away from Notion and what I use instead for managing my creative business.',
      platform: 'x',
      status: 'idea',
      views: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      engagementRate: 0,
      revenue: 0,
      tags: ['Productivity', 'Tools', 'Opinion'],
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      id: 'c-8',
      title: 'My $5K/Month Content System — Complete Walkthrough',
      description: 'The full system behind my content production that generates 5K monthly.',
      platform: 'youtube',
      status: 'developing',
      views: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      engagementRate: 0,
      revenue: 0,
      tags: ['Business', 'Content', 'System'],
      createdAt: daysAgo(4),
      updatedAt: daysAgo(2),
    },
  ],

  ideas: [
    {
      id: 'i-1',
      title: 'The App Everyone\'s Deleting Right Now',
      hook: 'This app just started bleeding users. Here\'s why everyone is leaving.',
      description: 'Trending app story — cover the viral tweet storm, the drama, and what it means for users.',
      platform: 'tiktok',
      category: 'Trending',
      tags: ['Viral', 'App', 'Drama'],
      viralScore: 9,
      status: 'idea',
      priority: 'high',
      trending: true,
      lastRefreshed: new Date().toISOString(),
      notes: 'Monitor daily for fresh angles. Check Twitter trending topics.',
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      id: 'i-2',
      title: 'This Product Went Viral Overnight — Here\'s the Backstory',
      hook: 'Nobody saw this product coming. And then it sold out in 3 hours.',
      description: 'Deep dive into the product that exploded on social this week — the brand, the story, the backlash.',
      platform: 'youtube',
      category: 'Trending',
      tags: ['Viral Product', 'TikTok Made Me Buy It', 'Trending'],
      viralScore: 8,
      status: 'idea',
      priority: 'high',
      trending: true,
      lastRefreshed: new Date().toISOString(),
      notes: 'Check TikTok shop trends and Twitter product launches daily.',
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      id: 'i-3',
      title: 'The $10 Hack Everyone Is Using to Go Viral',
      hook: 'There\'s a $10 tool that\'s getting people viral views and nobody is talking about it.',
      description: 'Break down the latest viral growth hack — is it real or is it a scam?',
      platform: 'tiktok',
      category: 'Trending',
      tags: ['Growth Hack', 'Viral', 'Tool'],
      viralScore: 9,
      status: 'ready_to_script',
      priority: 'high',
      trending: true,
      lastRefreshed: new Date().toISOString(),
      notes: 'Refresh with new hacks weekly — this space moves fast.',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
    {
      id: 'i-4',
      title: 'This Debate Is Dividing Everyone Right Now',
      hook: 'The internet is fighting about this right now. Here\'s both sides.',
      description: 'Balance both sides of a trending debate — no clickbait, just clear explanation.',
      platform: 'youtube',
      category: 'Trending',
      tags: ['Debate', 'Opinion', 'Culture'],
      viralScore: 8,
      status: 'idea',
      priority: 'medium',
      trending: true,
      lastRefreshed: new Date().toISOString(),
      notes: 'Check trending topics on X/Twitter and Reddit daily.',
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      id: 'i-5',
      title: 'I Tried the Viral Challenge Everyone Is Doing',
      hook: 'Everyone on your FYP is doing this challenge. I actually tried it.',
      description: 'Participate in the latest trending challenge and document results — funny and honest.',
      platform: 'tiktok',
      category: 'Trending',
      tags: ['Challenge', 'Viral', 'FYP'],
      viralScore: 8,
      status: 'scheduled',
      priority: 'high',
      trending: true,
      lastRefreshed: new Date().toISOString(),
      notes: 'Refresh challenge ideas every 2-3 days.',
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
    },
    {
      id: 'i-6',
      title: 'The Trend That\'s Quietly Replacing Influencers',
      hook: 'Influencers are losing views to something new. Here\'s what\'s taking over.',
      description: 'Analysis of the shift away from polished influencer content toward raw, authentic formats.',
      platform: 'youtube',
      category: 'Trending',
      tags: ['Influencers', 'Trend', 'Content Shift'],
      viralScore: 7,
      status: 'idea',
      priority: 'medium',
      trending: true,
      lastRefreshed: new Date().toISOString(),
      notes: 'Pull data from latest platform reports.',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
    {
      id: 'i-7',
      title: 'This Sound Is on Every Video Right Now',
      hook: 'You\'ve heard this sound 100 times today. Here\'s the story behind it.',
      description: 'The origin story of the trending audio — who made it, how it spread, and what\'s next.',
      platform: 'tiktok',
      category: 'Trending',
      tags: ['Sound', 'Viral Audio', 'Trend'],
      viralScore: 8,
      status: 'idea',
      priority: 'high',
      trending: true,
      lastRefreshed: new Date().toISOString(),
      notes: 'Check TikTok trending sounds every morning.',
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      id: 'i-8',
      title: 'The Creator System That 10x\'d My Output',
      hook: 'I rebuilt my entire content system. Here\'s what actually works in 2025.',
      description: 'My complete creator workflow — planning, scripting, recording, editing — the full system.',
      platform: 'youtube',
      category: 'Productivity',
      tags: ['Workflow', 'System', 'Creator Tips'],
      viralScore: 7,
      status: 'developing',
      priority: 'high',
      notes: 'Keep updated with new tools as they release.',
      createdAt: daysAgo(10),
      updatedAt: daysAgo(2),
    },
  ],

  scripts: [
    {
      id: 's-1',
      contentId: 'c-1',
      title: 'AI Tools 30-Day Experiment Script',
      hook: 'For 30 days, I replaced my entire workflow with AI tools. Here\'s what happened.',
      introduction: 'Before we dive in, let me be clear: I wasn\'t looking to replace myself. I was looking to amplify myself. 30 days, every tool I could find, every workflow that could be automated. Let\'s go.',
      body: 'Let me start with the tools that actually delivered.\n\n[Tool 1: Content ideation]\nI used AI for brainstorming. Not to replace my creative instincts, but to break through the blank-page paralysis I get every Sunday night.\n\n[Tool 2: Writing assistance]\nFor scripting, I used AI to generate first drafts. Then I rewrote everything in my voice. The result was 3x more content, zero loss of authenticity.\n\n[Tool 3: Video editing]\nThe biggest surprise. AI-assisted editing cut my post-production time from 4 hours to 45 minutes.',
      examples: 'Example: My most-viewed video this month was scripted entirely with AI assistance. 48,000 views in 72 hours.',
      cta: 'If you want the full list of tools and my exact workflow, it\'s linked below. And drop a comment — what AI tool are you using right now?',
      notes: 'Adjust pacing in middle section. The editing segment lands best.',
      wordCount: 1240,
      charCount: 7420,
      createdAt: daysAgo(14),
      updatedAt: daysAgo(14),
      versions: [],
    },
    {
      id: 's-2',
      contentId: 'c-2',
      title: 'Build SaaS in 48 Hours Script',
      hook: 'Most developers spend 6 months building something. I spent 48 hours. Here\'s the exact playbook.',
      introduction: 'I\'m going to show you the exact system I use to go from idea to deployed product in 48 hours. Not a demo. Not a tutorial. A real, live, paying product.',
      body: 'Hour 1-8: Validation and stack\nDon\'t start coding until you\'ve validated. I use Google Forms surveys, Twitter polls, and one Reddit post. If 50 people say they\'d pay for it, I build it.\n\nHour 9-24: Core features only\nI ship the absolute minimum. Auth, one main action, payment. That\'s it. Everything else is v2.\n\nHour 25-40: Design and polish\nThis is where most people stop. But the stuff that makes you money is here. Micro-interactions, onboarding, empty states.\n\nHour 41-48: Deploy and test',
      examples: 'SaaS #1 took 48 hours. It made $3,400 in month one. Not viral. Just clean execution.',
      cta: 'Full code is available on my GitHub. Link below. If you want the Notion template I use for project planning, it\'s in the description.',
      notes: 'Strongest hook is the "48 hours" framing. Lean into it more at the start.',
      wordCount: 1580,
      charCount: 9480,
      createdAt: daysAgo(21),
      updatedAt: daysAgo(10),
      versions: [],
    },
    {
      id: 's-3',
      title: 'Morning Routine for Creators Script',
      hook: 'Your morning is either making you or breaking you as a creator. Here\'s mine.',
      introduction: 'I used to wake up at noon, feel immediately behind, and spend the whole day playing catch-up. Then I rebuilt my morning from scratch. This is what I do every single day now.',
      body: 'Block 1: 6-7 AM — Physical (not digital)\nNo phone for the first hour. I stretch, make coffee, and sit with a physical notebook. This isn\'t woo-woo. It\'s neuroscience.\n\nBlock 2: 7-8 AM — Content planning\nI open my CRM — that\'s ClipFlow — and review what\'s scheduled. I write tomorrow\'s hook. That\'s it. Not a full script. Just the hook.\n\nBlock 3: 8-9 AM — Deep work\nRecording or writing. Nothing else. Phone in another room, notifications off.',
      examples: 'After 90 days on this routine: I went from 2 videos per week to 4. Without burning out.',
      cta: 'Try just one of these blocks for one week. Report back in the comments.',
      notes: 'Keep tone conversational, not preachy.',
      wordCount: 890,
      charCount: 5340,
      createdAt: daysAgo(12),
      updatedAt: daysAgo(12),
      versions: [],
    },
    {
      id: 's-4',
      title: 'AI Writing Workflow Script',
      hook: 'I wrote 30 videos last month. Here\'s how AI helps without making me sound robotic.',
      introduction: 'I know what you\'re thinking. AI-generated content sounds robotic. Generic. soulless. I thought the same thing. Then I figured out how to use it as a collaborator, not a replacement.',
      body: 'Step 1: Outlining with AI\nI give AI the topic, the target length, and three key points I want to make. It gives me an outline. I rewrite the outline.\n\nStep 2: First draft with AI\nI feed my rewritten outline into AI and ask for a first draft. Then I read it out loud.\n\nStep 3: The voice rewrite\nThis is the secret. I delete the first line of every paragraph. Write it myself. That\'s where my voice lives.\n\nStep 4: Tighten and ship\nCut 20% of the words. Add one personal story. Done.',
      examples: 'The video I made using this workflow: 48,200 views. My highest-performing non-tutorial video ever.',
      cta: 'My full AI writing template is in the description. Use it, adapt it, make it yours.',
      notes: 'Emphasize that AI is the accelerator, not the driver.',
      wordCount: 1100,
      charCount: 6600,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
      versions: [],
    },
    {
      id: 's-5',
      title: 'Small Creator Sponsorship Script',
      hook: 'I had 3K followers. Here\'s how I closed a $2,000 sponsorship deal.',
      introduction: 'Brands don\'t care about follower counts. They care about audience trust. Here\'s how I pitched a $2K deal with a tiny following — and how you can too.',
      body: 'The pitch deck I used:\n1. Audience breakdown — not just demographics, but engagement quality\n2. Three examples of previous work — even if unpaid\n3. A specific idea for how I\'d integrate their product naturally\n4. Social proof from my comments and DMs\n\nThe key insight: I didn\'t pitch myself as an influencer. I pitched myself as a converter.',
      examples: 'Brand paid $2,000 for one video. I delivered 4,200 clicks to their landing page. That\'s a $0.47 cost per click.',
      cta: 'If you want my exact pitch template, DM me on Twitter. First 20 people get it free.',
      notes: 'End with the stat, not the CTA. The stat lands stronger.',
      wordCount: 720,
      charCount: 4320,
      createdAt: daysAgo(9),
      updatedAt: daysAgo(9),
      versions: [],
    },
  ],

  sponsors: [
    {
      id: 'sp-1',
      company: 'Notion',
      contact: 'Sarah Chen',
      email: 'sarah.chen@notion.so',
      campaign: 'Product Integration — Notion Template Showcase',
      dealValue: 1500,
      status: 'completed',
      paymentStatus: 'paid',
      deadline: daysAgo(5),
      notes: 'Created a dedicated Notion workspace template for creators. 3-video series. All approved and published.',
      createdAt: daysAgo(30),
      updatedAt: daysAgo(5),
    },
    {
      id: 'sp-2',
      company: 'Vercel',
      contact: 'James Park',
      email: 'james@vercel.com',
      campaign: 'Deployment Workflow Tutorial',
      dealValue: 2200,
      status: 'in_progress',
      paymentStatus: 'partial',
      deadline: daysFromNow(14),
      notes: 'Two videos: beginner deploy guide + advanced Next.js optimization. First video delivered, second in editing.',
      createdAt: daysAgo(25),
      updatedAt: daysAgo(3),
    },
    {
      id: 'sp-3',
      company: 'Raycast',
      contact: 'Ana Torres',
      email: 'ana@raycast.com',
      campaign: 'Developer Productivity Workflow',
      dealValue: 800,
      status: 'negotiating',
      paymentStatus: 'pending',
      deadline: daysFromNow(21),
      notes: 'Interested in a 60-second shorts format. Counter-offered at $1,000. Waiting on response.',
      createdAt: daysAgo(8),
      updatedAt: daysAgo(2),
    },
    {
      id: 'sp-4',
      company: 'Descript',
      contact: 'Marcus Webb',
      email: 'marcus@descript.com',
      campaign: 'Video Editing Workflow Integration',
      dealValue: 1800,
      status: 'contacted',
      paymentStatus: 'pending',
      deadline: daysFromNow(30),
      notes: 'Sent initial outreach email. No response yet. Follow up in 3 days.',
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
    },
  ],

  calendar: [
    { id: 'cal-1', contentId: 'c-3', title: 'This Workflow Changed How I Create Content', platform: 'tiktok', date: daysFromNow(2), status: 'scheduled' },
    { id: 'cal-2', contentId: 'c-1', title: 'I Tried AI Tools for 30 Days', platform: 'youtube', date: daysAgo(3), status: 'published' },
    { id: 'cal-3', contentId: 'c-2', title: 'Build This SaaS in 48 Hours', platform: 'youtube', date: daysAgo(10), status: 'published' },
  ],

  library: [
    {
      id: 'lib-1',
      name: 'Thumbnail Template v3.psd',
      type: 'thumbnail',
      size: 48000000,
      url: '',
      category: 'Templates',
      createdAt: daysAgo(20),
    },
    {
      id: 'lib-2',
      name: 'Intro Animation.mp4',
      type: 'video',
      size: 124000000,
      url: '',
      category: 'B-Roll',
      createdAt: daysAgo(15),
    },
    {
      id: 'lib-3',
      name: 'AI Tools Script Final.docx',
      type: 'script',
      size: 45000,
      url: '',
      category: 'Scripts',
      createdAt: daysAgo(14),
    },
    {
      id: 'lib-4',
      name: 'Studio Background.png',
      type: 'image',
      size: 8900000,
      url: '',
      category: 'Overlays',
      createdAt: daysAgo(30),
    },
    {
      id: 'lib-5',
      name: 'Content Calendar 2025.xlsx',
      type: 'document',
      size: 120000,
      url: '',
      category: 'Planning',
      createdAt: daysAgo(45),
    },
  ],

  settings: {
    profile: {
      name: 'Mouad Sehli',
      handle: 'muad.sehli',
      avatar: '',
      bio: 'Content creator & developer. Building in public. Tech, SaaS, and productivity content.',
    },
    preferences: {
      platforms: ['youtube', 'tiktok', 'instagram'],
      categories: ['Tech', 'Productivity', 'Business', 'AI'],
      weeklyGoal: 3,
    },
    notifications: {
      email: true,
      push: true,
      inApp: true,
      weeklyDigest: true,
    },
    onboardingComplete: false,
    theme: 'dark',
  },
}
