'use client'

import { useState, useEffect } from 'react'
import { Sparkles, Copy, Check, RefreshCw, Save, X, ExternalLink, ChevronRight } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Select } from '@/components/ui/select'
import { Dialog, DialogHeader, DialogTitle, DialogBody, DialogFooter } from '@/components/ui/dialog'
import { Badge } from '@/components/ui/badge'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'
import { generateScript, parseScriptOutput, type ParsedScript, testAIConnection } from '@/lib/ai'
import type { Platform } from '@/lib/types'

interface AiScriptGeneratorProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  initialTopic?: string
  initialPlatform?: Platform
  onSave?: (data: {
    title: string
    hook: string
    introduction: string
    body: string
    examples: string
    cta: string
    notes: string
    wordCount: number
    charCount: number
  }) => void
}

const platformOptions = [
  { value: 'youtube', label: 'YouTube' },
  { value: 'tiktok', label: 'TikTok' },
  { value: 'instagram', label: 'Instagram' },
  { value: 'x', label: 'X (Twitter)' },
  { value: 'linkedin', label: 'LinkedIn' },
]

const contentTypeOptions = [
  { value: 'Tutorial', label: 'Tutorial / How-to' },
  { value: 'Commentary', label: 'Commentary / Opinion' },
  { value: 'Review', label: 'Review' },
  { value: 'Listicle', label: 'Listicle / Top 5' },
  { value: 'Storytime', label: 'Storytime / Personal' },
  { value: 'Educational', label: 'Educational / Explainer' },
  { value: 'Reaction', label: 'Reaction / Response' },
]

const toneOptions = [
  { value: 'Professional', label: 'Professional' },
  { value: 'Casual', label: 'Casual & Friendly' },
  { value: 'Provocative', label: 'Provocative / Edgy' },
  { value: 'Educational', label: 'Educational' },
  { value: 'Entertaining', label: 'Entertaining / Fun' },
]

const durationOptions = [
  { value: 'Under 1 min', label: 'Under 1 min' },
  { value: '1-3 min', label: '1-3 min' },
  { value: '3-7 min', label: '3-7 min' },
  { value: '7-15 min', label: '7-15 min' },
  { value: '15+ min', label: '15+ min' },
]

export function AiScriptGenerator({ open, onOpenChange, initialTopic = '', initialPlatform = 'youtube', onSave }: AiScriptGeneratorProps) {
  const [topic, setTopic] = useState(initialTopic)
  const [platform, setPlatform] = useState<Platform>(initialPlatform)
  const [contentType, setContentType] = useState('Tutorial')
  const [tone, setTone] = useState('Casual')
  const [duration, setDuration] = useState('3-7 min')
  const [generating, setGenerating] = useState(false)
  const [result, setResult] = useState<ParsedScript | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState<string | null>(null)
  const [showSaveForm, setShowSaveForm] = useState(false)
  const [saveTitle, setSaveTitle] = useState('')

  const hasApiKey = typeof window !== 'undefined' && !!localStorage.getItem('clipflow-openai-key')

  useEffect(() => {
    if (initialTopic) setTopic(initialTopic)
    if (initialPlatform) setPlatform(initialPlatform)
  }, [initialTopic, initialPlatform])

  const handleGenerate = async () => {
    if (!topic.trim()) { toast.error('Please enter a topic'); return }
    setGenerating(true)
    setError(null)
    setResult(null)
    try {
      const res = await generateScript(topic, platform, contentType, tone, duration)
      setResult(res)
    } catch (err: any) {
      setError(err.message || 'Generation failed. Check your API key in Settings.')
    } finally {
      setGenerating(false)
    }
  }

  const handleCopy = (text: string, key: string) => {
    navigator.clipboard.writeText(text)
    setCopied(key)
    toast.success('Copied!')
    setTimeout(() => setCopied(null), 2000)
  }

  const handleSave = () => {
    if (!result || !onSave) return
    const body = result.body.join('\n\n')
    const notes = `[Generated by AI]\nPlatform: ${platform}\nType: ${contentType}\nTone: ${tone}\nDuration: ${duration}\n\nWord count: ${result.wordCount}`
    onSave({
      title: saveTitle || topic,
      hook: result.hook,
      introduction: result.introduction,
      body,
      examples: '',
      cta: result.cta,
      notes,
      wordCount: result.wordCount,
      charCount: result.wordCount * 5,
    })
    toast.success('Script saved to library')
    onOpenChange(false)
    setResult(null)
    setShowSaveForm(false)
    setSaveTitle('')
  }

  const handleClose = () => {
    onOpenChange(false)
    setTimeout(() => {
      setResult(null)
      setError(null)
      setShowSaveForm(false)
    }, 300)
  }

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogHeader>
        <DialogTitle className="flex items-center gap-2">
          <Sparkles size={16} className="text-violet" />
          AI Script Generator
        </DialogTitle>
      </DialogHeader>
      <DialogBody className="p-0">
        {!hasApiKey ? (
          <div className="p-6 text-center space-y-3">
            <div className="w-12 h-12 rounded-full bg-violet/10 flex items-center justify-center mx-auto">
              <Sparkles size={20} className="text-violet" />
            </div>
            <div>
              <p className="text-sm font-medium text-white">API Key Required</p>
              <p className="text-xs text-white/40 mt-1">Add your OpenAI API key in Settings to use AI generation.</p>
            </div>
            <Button variant="primary" size="sm" onClick={() => { handleClose(); window.location.href = '/settings' }}>
              Go to Settings <ChevronRight size={14} />
            </Button>
          </div>
        ) : generating ? (
          <div className="p-12 text-center space-y-4">
            <div className="w-12 h-12 rounded-full border-2 border-violet border-t-transparent animate-spin mx-auto" />
            <div>
              <p className="text-sm font-medium text-white">Crafting your script...</p>
              <p className="text-xs text-white/40 mt-1">This usually takes 5-15 seconds</p>
            </div>
          </div>
        ) : result ? (
          <div className="max-h-[60vh] overflow-y-auto space-y-5 p-5">
            {/* Hooks */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-mono text-violet uppercase tracking-wider">Hook Options</label>
                <div className="flex gap-1">
                  {result.hooks.slice(0, 1).map((h, i) => (
                    <button key={i} onClick={() => handleCopy(h, `hook-${i}`)}
                      className="text-xs px-2 py-1 rounded bg-white/[0.04] text-white/40 hover:text-white/70 flex items-center gap-1">
                      {copied === `hook-${i}` ? <Check size={10} className="text-emerald" /> : <Copy size={10} />}
                      {copied === `hook-${i}` ? 'Copied' : 'Copy'}
                    </button>
                  ))}
                </div>
              </div>
              <div className="space-y-2">
                {result.hooks.map((h, i) => (
                  <button key={i} onClick={() => handleCopy(h, `hook-${i}`)}
                    className="w-full text-left p-3 rounded-lg bg-white/[0.03] border border-white/[0.06] hover:border-violet/30 transition-colors group">
                    <span className="text-[10px] font-mono text-white/20 mr-2">{i + 1}</span>
                    <span className="text-sm text-white/70 group-hover:text-white">{h}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Titles */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-mono text-violet uppercase tracking-wider">Title Options</label>
                {result.titles[0] && (
                  <button onClick={() => handleCopy(result.titles[0], 'title-0')}
                    className="text-xs px-2 py-1 rounded bg-white/[0.04] text-white/40 hover:text-white/70 flex items-center gap-1">
                    {copied === 'title-0' ? <Check size={10} className="text-emerald" /> : <Copy size={10} />}
                    {copied === 'title-0' ? 'Copied' : 'Copy Top'}
                  </button>
                )}
              </div>
              <div className="space-y-2">
                {result.titles.map((t, i) => (
                  <button key={i} onClick={() => handleCopy(t, `title-${i}`)}
                    className="w-full text-left p-3 rounded-lg bg-white/[0.03] border border-white/[0.06] hover:border-violet/30 transition-colors group">
                    <span className="text-[10px] font-mono text-white/20 mr-2">{i + 1}</span>
                    <span className="text-sm text-white/70 group-hover:text-white">{t}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Script Outline */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-mono text-violet uppercase tracking-wider">Script Outline</label>
                <div className="flex items-center gap-2">
                  <Badge variant="default" className="text-[10px]">{result.wordCount} words · {result.readTime}</Badge>
                  <button onClick={() => handleCopy(result.raw, 'all')}
                    className="text-xs px-2 py-1 rounded bg-white/[0.04] text-white/40 hover:text-white/70 flex items-center gap-1">
                    {copied === 'all' ? <Check size={10} className="text-emerald" /> : <Copy size={10} />}
                    Copy All
                  </button>
                </div>
              </div>
              <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-4 space-y-4">
                {result.hook && (
                  <div>
                    <p className="text-[10px] font-mono text-violet uppercase tracking-wider mb-1.5">Hook</p>
                    <p className="text-sm text-white/70 leading-relaxed">{result.hook}</p>
                  </div>
                )}
                {result.introduction && (
                  <div>
                    <p className="text-[10px] font-mono text-violet uppercase tracking-wider mb-1.5">Introduction</p>
                    <p className="text-sm text-white/70 leading-relaxed">{result.introduction}</p>
                  </div>
                )}
                {result.body.map((point, i) => (
                  <div key={i}>
                    <p className="text-[10px] font-mono text-violet uppercase tracking-wider mb-1.5">Main Point {i + 1}</p>
                    <p className="text-sm text-white/70 leading-relaxed">{point}</p>
                  </div>
                ))}
                {result.cta && (
                  <div>
                    <p className="text-[10px] font-mono text-emerald uppercase tracking-wider mb-1.5">Call to Action</p>
                    <p className="text-sm text-white/70 leading-relaxed">{result.cta}</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        ) : error ? (
          <div className="p-6 text-center space-y-3">
            <div className="w-12 h-12 rounded-full bg-red-500/10 flex items-center justify-center mx-auto">
              <X size={20} className="text-red-400" />
            </div>
            <div>
              <p className="text-sm font-medium text-white">Generation Failed</p>
              <p className="text-xs text-white/40 mt-1">{error}</p>
            </div>
            <Button variant="secondary" size="sm" onClick={() => setError(null)}>
              <RefreshCw size={14} /> Try Again
            </Button>
          </div>
        ) : (
          /* Form */
          <div className="p-5 space-y-4">
            <Textarea
              label="Topic / Content Idea"
              value={topic}
              onChange={e => setTopic(e.target.value)}
              placeholder="e.g. Why everyone is burned out by hustle culture..."
              rows={3}
            />
            <div className="grid grid-cols-2 gap-3">
              <Select label="Platform" value={platform} onValueChange={v => setPlatform(v as Platform)} options={platformOptions} id="ai-platform" />
              <Select label="Content Type" value={contentType} onValueChange={setContentType} options={contentTypeOptions} id="ai-type" />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <Select label="Tone" value={tone} onValueChange={setTone} options={toneOptions} id="ai-tone" />
              <Select label="Duration" value={duration} onValueChange={setDuration} options={durationOptions} id="ai-duration" />
            </div>
          </div>
        )}
      </DialogBody>

      <DialogFooter className="p-4 border-t border-white/[0.06]">
        {result ? (
          <div className="flex items-center gap-2">
            <Button variant="secondary" size="sm" onClick={() => { setResult(null); setError(null) }}>
              <RefreshCw size={14} /> Regenerate
            </Button>
            <Button variant="secondary" size="sm" onClick={handleCopy.bind(null, result.raw, 'all')}>
              <Copy size={14} /> Copy All
            </Button>
            <div className="flex-1" />
            {showSaveForm ? (
              <div className="flex items-center gap-2">
                <input
                  value={saveTitle}
                  onChange={e => setSaveTitle(e.target.value)}
                  placeholder="Script title..."
                  className="bg-white/[0.03] border border-white/[0.07] rounded-lg px-3 py-1.5 text-sm text-white placeholder:text-white/20 outline-none focus:border-violet/50 w-48"
                  autoFocus
                />
                <Button variant="primary" size="sm" onClick={handleSave}>
                  <Save size={14} /> Save
                </Button>
              </div>
            ) : (
              <Button variant="primary" size="sm" onClick={() => setShowSaveForm(true)}>
                <Save size={14} /> Save as Script
              </Button>
            )}
          </div>
        ) : (
          <div className="flex items-center gap-2">
            <Button variant="secondary" onClick={handleClose}>Cancel</Button>
            <Button variant="primary" onClick={handleGenerate} disabled={!topic.trim() || !hasApiKey}>
              <Sparkles size={14} /> Generate Script
            </Button>
          </div>
        )}
      </DialogFooter>
    </Dialog>
  )
}
